CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL CHECK (btrim(name) <> ''),
    login TEXT NOT NULL UNIQUE CHECK (btrim(login) <> '' AND login = lower(btrim(login))),
    password_hash TEXT NOT NULL CHECK (btrim(password_hash) <> ''),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE clients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL CHECK (btrim(name) <> ''),
    document TEXT NOT NULL UNIQUE CHECK (document ~ '^[0-9]+$'),
    birth_date DATE,
    phone TEXT NOT NULL CHECK (btrim(phone) <> ''),
    secondary_phone TEXT,
    street TEXT NOT NULL CHECK (btrim(street) <> ''),
    neighborhood TEXT NOT NULL CHECK (btrim(neighborhood) <> ''),
    address_number TEXT NOT NULL CHECK (btrim(address_number) <> ''),
    complement TEXT,
    postal_code TEXT,
    address_type TEXT NOT NULL CHECK (btrim(address_type) <> ''),
    address_reference TEXT,
    position INTEGER NOT NULL DEFAULT 0 CHECK (position >= 0),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL CHECK (btrim(name) <> ''),
    purchase_price NUMERIC(14,2) NOT NULL CHECK (purchase_price >= 0),
    sale_price NUMERIC(14,2) NOT NULL CHECK (sale_price > 0),
    image_url TEXT,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE billing_periods (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    period_start DATE NOT NULL UNIQUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT billing_period_first_day CHECK (period_start = date_trunc('month', period_start)::date)
);

CREATE TABLE invoices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id BIGINT NOT NULL REFERENCES clients(id) ON DELETE RESTRICT,
    billing_period_id BIGINT NOT NULL REFERENCES billing_periods(id) ON DELETE RESTRICT,
    status TEXT NOT NULL CHECK (status IN ('issued', 'canceled')),
    observation TEXT,
    account_balance_before_issue NUMERIC(15,2) NOT NULL,
    products_total NUMERIC(15,2) NOT NULL CHECK (products_total > 0),
    account_balance_after_charge NUMERIC(15,2) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    canceled_at TIMESTAMPTZ,
    cancellation_reason TEXT,
    CONSTRAINT invoice_account_snapshot_consistent CHECK (
        account_balance_after_charge = account_balance_before_issue + products_total
    ),
    CONSTRAINT invoice_cancellation_state_consistent CHECK (
        (status = 'issued' AND canceled_at IS NULL AND cancellation_reason IS NULL)
        OR
        (
            status = 'canceled'
            AND canceled_at IS NOT NULL
            AND cancellation_reason IS NOT NULL
            AND btrim(cancellation_reason) <> ''
        )
    ),
    CONSTRAINT invoices_id_client_unique UNIQUE (id, client_id)
);

CREATE UNIQUE INDEX uq_invoices_active_client_period
    ON invoices (client_id, billing_period_id)
    WHERE status = 'issued';
CREATE INDEX idx_invoices_period_client ON invoices (billing_period_id, client_id);
CREATE INDEX idx_invoices_fifo ON invoices (client_id, billing_period_id, created_at, id)
    WHERE status = 'issued';

CREATE TABLE invoice_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id BIGINT NOT NULL REFERENCES invoices(id) ON DELETE RESTRICT,
    product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE RESTRICT,
    product_name TEXT NOT NULL CHECK (btrim(product_name) <> ''),
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    unit_purchase_price NUMERIC(14,2) NOT NULL CHECK (unit_purchase_price >= 0),
    unit_sale_price NUMERIC(14,2) NOT NULL CHECK (unit_sale_price > 0),
    purchase_total NUMERIC(15,2) GENERATED ALWAYS AS (
        (unit_purchase_price * quantity)::NUMERIC(15,2)
    ) STORED,
    sale_total NUMERIC(15,2) GENERATED ALWAYS AS (
        (unit_sale_price * quantity)::NUMERIC(15,2)
    ) STORED,
    profit_total NUMERIC(15,2) GENERATED ALWAYS AS (
        ((unit_sale_price - unit_purchase_price) * quantity)::NUMERIC(15,2)
    ) STORED,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_invoice_items_product UNIQUE (invoice_id, product_id)
);

CREATE INDEX idx_invoice_items_invoice ON invoice_items (invoice_id);
CREATE INDEX idx_invoice_items_product ON invoice_items (product_id);

CREATE TABLE payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id BIGINT NOT NULL REFERENCES clients(id) ON DELETE RESTRICT,
    amount NUMERIC(15,2) NOT NULL CHECK (amount > 0),
    effective_date DATE NOT NULL,
    observation TEXT,
    status TEXT NOT NULL CHECK (status IN ('posted', 'reversed')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    reversed_at TIMESTAMPTZ,
    reversal_reason TEXT,
    CONSTRAINT payment_reversal_state_consistent CHECK (
        (status = 'posted' AND reversed_at IS NULL AND reversal_reason IS NULL)
        OR
        (
            status = 'reversed'
            AND reversed_at IS NOT NULL
            AND reversal_reason IS NOT NULL
            AND btrim(reversal_reason) <> ''
        )
    ),
    CONSTRAINT payments_id_client_unique UNIQUE (id, client_id)
);

CREATE INDEX idx_payments_client_fifo ON payments (client_id, effective_date, created_at, id);
CREATE INDEX idx_payments_effective_client ON payments (effective_date, client_id, id);

CREATE TABLE payment_allocations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id BIGINT NOT NULL REFERENCES clients(id) ON DELETE RESTRICT,
    payment_id BIGINT NOT NULL,
    invoice_id BIGINT NOT NULL,
    amount NUMERIC(15,2) NOT NULL CHECK (amount > 0),
    status TEXT NOT NULL CHECK (status IN ('active', 'reversed')),
    allocated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    reversed_at TIMESTAMPTZ,
    reversal_kind TEXT,
    reversal_reason TEXT,
    CONSTRAINT fk_payment_allocations_payment_client
        FOREIGN KEY (payment_id, client_id) REFERENCES payments(id, client_id) ON DELETE RESTRICT,
    CONSTRAINT fk_payment_allocations_invoice_client
        FOREIGN KEY (invoice_id, client_id) REFERENCES invoices(id, client_id) ON DELETE RESTRICT,
    CONSTRAINT payment_allocation_reversal_state_consistent CHECK (
        (status = 'active' AND reversed_at IS NULL AND reversal_kind IS NULL AND reversal_reason IS NULL)
        OR
        (
            status = 'reversed'
            AND reversed_at IS NOT NULL
            AND reversal_kind IN ('invoice_cancellation', 'payment_reversal', 'fifo_reallocation')
            AND reversal_reason IS NOT NULL
            AND btrim(reversal_reason) <> ''
        )
    )
);

CREATE UNIQUE INDEX uq_payment_allocations_active_pair
    ON payment_allocations (payment_id, invoice_id)
    WHERE status = 'active';
CREATE INDEX idx_payment_allocations_active_invoice
    ON payment_allocations (invoice_id)
    WHERE status = 'active';
CREATE INDEX idx_payment_allocations_active_payment
    ON payment_allocations (payment_id)
    WHERE status = 'active';
